tests/run_python_unittests.sh
tests/setup_env_for_python_unittests.sh

Update the scripts for running the unit tests and report coverage properly.

Unit test script and coverage report

---

tests/run_python_unittests.sh
tests/setup_env_for_python_unittests.sh
tests/test_FileSR.py
tests/test_ISCSISR.py
tests/test_ISOSR.py
tests/test_LVHDSR.py
tests/test_LVHDoFCoESR.py
tests/test_NFSSR.py
tests/test_SMBSR.py
tests/test_SRCommand.py
tests/test_blktap2.py
tests/test_cleanup.py
tests/test_devscan.py
tests/test_lock.py
tests/test_lvutil.py
tests/test_nfs.py
tests/test_refcounter.py
tests/test_scsiutil.py
tests/test_testlib.py
tests/test_trim_util.py
tests/test_udevSR.py

Miscellaneous updates to unit tests.

Update unit tests

---

drivers/blktap2.py
drivers/coalesce-leaf
drivers/resetvdis.py

As suggested by Bob Ball.
Suggested-by: Bob Ball bob.ball@citrix.com
Signed-off-by: Zheng Li dev@zheng.li

CA-188721: Fix a few potential hazards of XAPI session leaking

---

drivers/on-slave

Signed-off-by: Chandrika Srinivasan <chandrika.srinivasan@citrix.com>
Reviewed-by: Mark Syms <mark.syms@citrix.com>

CA-240718: Fail multi-step plugins on first failure

---

drivers/FileSR.py

Reviewed-by: Stefano Panella <stefano.panella@citrix.com>

CA-260961: ensure failure generates adequate logging

---

drivers/mpath_dmp.py
tests/test_mpath_dmp.py

Signed-off-by: Stefano Panella <stefano.panella@citrix.com>
Reviewed-by: Germano Percossi <germano.percossi@citrix.com>

CA-255945: fix race on mkdir

---

drivers/VDI.py
tests/test_cbt.py

And update unit tests for CBT chain setup and verification

CA-270011: Handle snapshotting a snapshot in a CBT chain

---

drivers/LVHDSR.py

Reviewed-by: Chandrika Srinivasan <chandrika.srinivasan@citrix.com>

CA-276601: cleanup refcounts when deleting unused volume

---

drivers/FileSR.py

... which seems possible by other components in the system.
Signed-off-by: Zheng Li <zheng.li3@citrix.com>

CA-288100: in case the VDI is removed in between

---

drivers/cleanup.py

SMGC's leaf coalescing isn't meant to happen on VDIs with caching
enabled.
It wasn't an issue before CP-18840, when the leaf coalescing was
completely disabled on file-based SR anyway. With CP-18840, we need
to be able more careful about this. This patch disables leaf
coalescing on cache-enabled VDIs and protect their VHD tree height
from being changed by leaf coalesce (to avoid disabling/enabling
cache unintentionally).
Signed-off-by: Zheng Li <zheng.li3@citrix.com>

CA-290491: do not leaf coalesce VDIs with allow_caching=true

---

drivers/lvutil.py

CA-247723: extend timeout and log lsof if still busy afterwards

---

drivers/blktap2.py

CA-292268: Retry tap-ctl.Spawn on failure

---

multipath/multipath.conf

Blacklist nbd devices

---

drivers/FileSR.py

After the original leaf has been renamed, td-util is asked to create a
snapshot with the filename it originally had. This means that after
td-util creates the file there is a brief window before it finishes
populating it when an attempt to query it will fail because the file
contents are invalid.
If we instead create the new leaf with a temporary filename
(foo.vhd.new) and rename it afterwards, this window is converted into
one during which the file does not exist, a condition in which a query
attempt will be retried for up to 20 seconds.
If necessary, the window can be shrunk further by using links so that
the old and new names of the original leaf exist simultaneously until it
is time to rename the new leaf into place (this is necessary because
td-util's snapshot function requires the …

CA-292144 Avoid having an invalid leaf while taking a snapshot

---

drivers/iscsilib.py

Chap setting need to be removed if no chap requested.

CA-294975: ensure chap settings are removed from discovery db

---

drivers/lvutil.py

CA-247723: Use fuser to report on who has the device open

---

scripts/onequeue.sh

When systemd-udevd has run out of things to do and thinks it has no
workers left running, it kills everything in its control group except
itself.
In order to avoid a premature death in this circumstance, deliberately
escape into another control group which we know exists.

CA-295775 Escape from systemd-udevd's control group

---

drivers/cleanup.py

CA-296534: if we give up on snapshot-coalesce, don't fall through to live coalesce 

---

drivers/lvutil.py
drivers/scsiutil.py
drivers/trim_util.py

CP-27709: suppress error if blkdiscard fails on full provisioned lun

---

drivers/blktap2.py
drivers/plugins/__init__.py

Move logging to test plugin manager and out of common
production code.

CA-302773: move import of plugins until we need it.

---

drivers/vhdutil.py
tests/test_vhdutil.py

Signed-off-by: Gerald Elder-Vass <gerald.elder-vass@citrix.com>

Update MAX_VHD_SIZE to 2088960MiB (2040GiB).

---

drivers/blktap2.py

CP-30167: handle changed blkback kthread notification

---

tests/test_nfs.py

Update NFS unit tests to make intent clearer

---

drivers/lvutil.py

CA-247723: wait for udevadm settle in LVM create

---

udev/40-multipath.rules

CA-311551: do not trigger mpath count for nbd devices

---

drivers/mpathcount.py
udev/40-multipath.rules

CA-313960: ensure that mpathcount trigger correctly

---

drivers/cleanup.py

Signed-off-by: Chandrika Srinivasan <chandrika.srinivasan@citrix.com>

CA-316157: Check if any garbage collection needs to be done before going quiet

---

drivers/cleanup.py

CA-315152: gc_force needs to take gc_active lock not running

---

drivers/LVHDoISCSISR.py

CA-323050: check that at least one iSCSI session established

---

drivers/blktap2.py

CA-323394: Stop tapdisk process inheriting fds from sm process

---

tests/test_cleanup.py

CP-23299: add test for HFX-651

---

drivers/cleanup.py

CP-32203: report VHD sizes when abandoning leaf coalesce

---

drivers/EXTSR.py

Use ext4 for local ext SR

---

drivers/XE_SR_ERRORCODES.xml

CA-328536: fix typo in error message

---

Makefile
drivers/ISOSR.py
drivers/SMBSR.py
drivers/cifutils.py
drivers/util.py
mk/sm.spec.in
tests/test_ISOSR.py
tests/test_SMBSR.py
tests/test_cifutils.py
tests/test_utils.py
tests/testlib.py

Signed-off-by: ben sims <ben.sims@citrix.com>

CA-329845 - Remove usage of credentials file for CIF

---

drivers/lvutil.py
tests/test_lvutil.py

CA-324971: lock LVM commands to avoid concurrency clashes

---

mk/sm.spec.in
scripts/set-iscsi-initiator

CA-333441: Add script to update iscsi IQN and restart iscsid if needed

---

drivers/cifutils.py

Add additional logging to aid diagnosis for any future problems.

XSI-570 - Improve observability of cifutils

---

Makefile

CA-333441: install the set-iscsi-initiator script

---

drivers/blktap2.py
tests/test_blktap2.py

This has had minimal testing, (VM boot, reboot)
Travis does not appear to like this yet, Yet the the unit tests are fine locally??

CP-31856 - Return nbd socket as parameter to XAPI

---

drivers/cleanup.py

CA-335351: ensure async tasks are cleaned up

---

drivers/blktap2.py

CA-335771: call tap-ctl close with a timeout

---

drivers/EXTSR.py
drivers/NFSSR.py
drivers/SMBSR.py

CP-33292: add read caching capability flags

---

drivers/cleanup.py

CA-338619: log the hostname when asking slaves

---

tests/run_python_unittests.sh

Allow for running a subset of unit tests

---

drivers/mpathcount.py

CA-341777: pass args in the correct order

---

udev/65-multipath.rules

Even when path count isn't required

CA-343115: ensure device symlinks are created correctly

---

drivers/blktap2.py
tests/mocks/XenAPI/__init__.py
tests/test_blktap2.py
tests/test_cleanup.py

Before fixing CA-344254, add unit tests to cover the affected areas.

Add unit tests before bug fix

---

tests/run_python_unittests.sh
tests/test_cleanup.py

Preparation work for adding more tests

CA-344254: simplify test-cleanup and use a magicmock for xapi

---

drivers/SR.py
drivers/SRCommand.py

Address some flake8 issues

---

drivers/blktap2.py

CA-346590: log when activating flag removed

---

multipath/multipath.conf

Signed-off-by: Jaron Parsons <jaron@ixsystems.com>

Add TrueNAS ALUA support

---

drivers/cleanup.py

CA-349759: don't call srUpdate within a lock

---

tests/test_LVHDSR.py

CA-350871: add basic snapshot unit test

---

.github/workflows/main.yml

Trigger actions on pull requests as well

---

drivers/NFSSR.py
drivers/nfs.py
drivers/util.py
tests/test_NFSSR.py
tests/test_nfs.py
tests/test_utils.py

Signed-off-by: BenjiReis <benjamin.reis@vates.fr>

Support IPv6 in NFS

---

tests/lvmlib.py
tests/test_lvutil.py

Add test coverage of _lvmBugCleanup

---

drivers/EXTSR.py
drivers/LVHDSR.py
drivers/SR.py
tests/test_SR.py

CA-354692: check for device parameter in create/probe calls

---

drivers/cleanup.py
tests/test_cleanup.py

CA-356234: don't run repair if parent is raw

---

tests/test_cleanup.py

CA-356234: Fix SQ issues

---

drivers/BaseISCSI.py
drivers/ISOSR.py
drivers/LVHDSR.py
drivers/LVHDoHBASR.py
drivers/LVHDoISCSISR.py
drivers/SMBSR.py
drivers/VDI.py
drivers/blktap2.py
drivers/cleanup.py
drivers/iscsilib.py
drivers/lvmcache.py
drivers/lvutil.py
drivers/metadata.py
drivers/nfs.py
drivers/srmetadata.py
drivers/util.py
tests/flake8

CP-37498: Fix all E711 errors in SM 

---

.github/workflows/main.yml
base_requirements.txt
dev_requirements.txt
requirements.txt

Clarify the contents and usage of pip requirements files

---

drivers/VDI.py

These keys are used ephemerally as part of the GC chain relink and
blktap activation paths to interlock the two processes and may be removed
while the SR scan is occuring.

CA-359304: ignore relinking and activating tags in update_sm_config

---

multipath/multipath.conf

CP-38316: Dell requested that path checker be changed to readsector0

---

drivers/LVHDSR.py
tests/test_LVHDSR.py

Remove use of eval

---

drivers/XE_SR_ERRORCODES.xml
drivers/mpath_dmp.py

CA-369613: report errors correctly from multipath

---

tests/lvmlib.py

Update test lvmlib to use argparse

---

drivers/LVHDSR.py

CA-370572: relinking is a transient property, do not copy to clones

---

drivers/LVHDSR.py
drivers/lvutil.py

CA-372641: fix _expand_size for multipath

---

drivers/util.py

CA-372772: fix miscalculation of seek offset

---

drivers/trim_util.py
tests/test_trim_util.py

On a LUN which has provisioning_mode = full the blkdiscard ioctl will usually fail which is not entirely unexpected as the primary use case for blkdiscard here is to release unused blocks on a thinly provisioned LUN so that a SAN may reassign them to a different LUN if required. Leave the code making the call as it is possible that some SANs may still accept a blkdiscard on a fully provisioned LUN and usefully do something with the request, but do not propagate an error back to the user as it just creates confusion.

CP-27709: filter error messages about ioctl not supported in trim

---

Makefile
mk/sm.spec.in

Update Makefile so that the file is installed along with sm.
This is a follow-up to https://github.com/xapi-project/sm/pull/600. I since realized that it's the Makefile's responsibility to install the file.

Install /etc/multipath/conf.d/custom.conf

---

drivers/ISOSR.py

Location are of form: `[<ipv6>]:/path`

Support IPv6 for NFS ISO SR

---

drivers/DummySR.py
drivers/XE_SR_ERRORCODES.xml

Correct some error codes to ones which exist, and add a few new ones to cover calls which could not easily be corrected.

CA-253490 Add missing error codes

---

tests/test_NFSSR.py
tests/test_SMBSR.py

Ensure unit tests cover the modified error handling for attach in NFSSR and SMBSR

CA-387770 increase NFSSR and SMBSR test coverage

---

multipath/multipath.conf

See reference document from Dell's website - https://www.dell.com/support/kbdoc/en-uk/000124601/me4-md-series-combined-linux-mpio-multipath-conf

CP-49961: update multipath config for Dell arrays

---

drivers/cleanup.py
tests/test_cleanup.py

Also, log a summary of the snapshot coalesce process on completion

Ca 399644: if we make progress do not abort the GC or evaluate criteria

---

drivers/EXTSR.py
drivers/lvutil.py
scripts/storage-init
tests/lvmlib.py
tests/test_storage_init.py

And have lvcreate wipe signatures as well.

CA-404517: use wipefs to prepare the volume for storage-init

---

.github/workflows/main.yml
dev_requirements.txt
drivers/LUNperVDI.py
drivers/LVHDSR.py
drivers/SR.py
drivers/cleanup.py
drivers/iscsilib.py
drivers/mpathcount.py
drivers/resetvdis.py

We have been notified by Github that the Ubuntu 20.04 hosted runner is being shut down. Proactively update to ubuntu-latest before this casues issues.

Update actions to use Ubuntu latest
