xapi-project/sm

drivers/SRCommand.py
drivers/XE_SR_ERRORCODES.xml
tests/test_SRCommand.py

Added a catch for generic Exceptions in SRCommand.run(driver, driver_info).
This prints a xmlrpclib dump containing the details of the generic exception,
in the same way SR.SRExeption.toxml() does. In this way all unexpected errors
should be caught and printed in a syntax Xapi understands. A new error code
(1200) has also been defined in XE_SR_ERRORCODES.xml to broadly categorise
generic errors. Some tests have also been changed and updated to test throwing
exceptions in a more appropriate manner.
Signed-off-by: James Davis <james.davis1@citrix.com>
Reviewed-by: Mark Syms <mark.syms@citrix.com>

CA-218867: Handle exceptions and fail more elegantly

---

drivers/XE_SR_ERRORCODES.xml
drivers/mpath_dmp.py
multipath/multipath.conf
tests/test_mpath_dmp.py

By design, when multipath is enabled on a host, the storage manager is
expecting to handle any valid block device used by an SR.
There are cases where the user wants to use multipath along with other
SRs using block devices incompatible with multipath.
This modification will let SM proceed without enforcing multipath if
multipath believes that device has been explicitly blacklisted

Ignore multipath flag for blacklisted devices

---

drivers/iscsilib.py
tests/test_iscsilib.py

The iSCSI database is located /var/lib/iscsi instead of /etc/iscsi in recent
Linux distributions.
This fix resolves the following problems:
- On SCTX-2590 - the impact of this was that the connection using multiple
"c_iface"-s was not established, as the default interface was already
cached.
Based on looking at the code, this fix may also help in the following
scenarios
- iSCSI boot from SAN may have been broken, as the iSCSI connection state
for the root disk was not persisted across discoveries.
- If a storage array changes IP addresses, it doesn't even get discovered
after a reboot.
This commit does not introduce an explicit warning or failure, as we're
working on a replacement for this (Transport) code.
Signed-off-by: Robert Breker <robert.breker@citrix.com>
Reviewed-by: Germano …

    CA-263084: Fix path to iSCSI database

---

drivers/blktap2.py

If the parent of the VDI being activated also has a parent then exit.
Reviewed-by: Germano Percossi <germano.percossi@citrix.com>

CA-264210: Intellicache only supports a single base disk with deltas.

---

drivers/util.py

Reviewed-by: Germano Percossi <germano.percossi@citrix.com>

CA-267032: add ESRCH to list of acceptable errors in pid search

---

drivers/mpath_dmp.py
tests/test_mpath_dmp.py

Checks for multipath eligibility now include
* multipath -ll on SCSI ID to check if device is already multipathed
* Skip check if device path is not up yet
* Use all devices associated with a SCSI ID for the multipath -c check
Signed-off-by: Chandrika Srinivasan <chandrika.srinivasan@citrix.com>
Reviewed-by: Mark Syms <mark.syms@citrix.com>

CA-267460: Make device multipath eligibility check more robust

---

drivers/util.py

Reviewed-by: Stefano Panella <stefano.panella@citrix.com>

CA-277346: Fix flawed parsing of /proc/<pid>/cmdline, split on NUL

---

base_requirements.txt
dev_requirements.txt
tests/run_python_unittests.sh
tests/setup_env_for_python_unittests.sh

Ensure that unit tests use virtualenv when not in RPM build.
Reviewed-by: Chandrika Srinivasan <chandrika.srinivasan@citrix.com>

Rationalise installation of pip packages as much as possible

---

drivers/ISOSR.py
tests/test_ISOSR.py

Reviewed-by: Chandrika Srinivasan <chandrika.srinivasan@citrix.com>

CA-273731: call _testHost before trying to mount ISO SR NFS share

---

drivers/lvutil.py
tests/lvmlib.py
tests/test_lvutil.py

From SCTX-2673, rare occurence where the new LV could contain data
which causes a segfault in libblkid when scanning for signatures.
Which isn't required anyway as the next step is to apply a VHD image
format onto the volume.

CA-292103: do not scan for and clear signatures in new volumes

---

drivers/util.py

CA-295861: extract processname correctly when there are no arguments

---

Makefile
drivers/mpath_cli.py
drivers/mpathcount.py
mk/sm.spec.in
multipath/mpcount.service
scripts/onequeue.sh
scripts/udevmpath.sh
udev/40-multipath.rules

Sending multipath UDEV events via a systemd service into atd does not
work very well at getting them processed; systemd drops attempts to
start any service which is already in the process of starting (which
loses information in the case of an event storm) while atd is a batch
processor designed to do things "at some vague time in the future which
could turn out to be never if the system load is higher than some
number".
A better solution is to use neither, and when we are scanning for
updates because of a UDEV event, use a simple wait/run lock pair to
rate-limit scans while ensuring that every event is followed by a scan
as soon as possible so its new state is detected.
We can now remove the 2 second sleep in drivers/mpathcount.py
In addition, the match_pathup function in …

CA-295775 Fix handling of multipath events

---

drivers/srmetadata.py

Change getMetadataLength() to read the header in the same way that
requiresUpgrade() does, and add some checking to unpackHeader() so that
it will raise an error if the header is invalid.

CA-292588 Add debug to header checking

---

drivers/blktap2.py

Add some additional information to an extremely rare assert, to make it
a bit easier to work out what's going on if it ever happens again.

CA-297698 improve assert message

---

drivers/EXTSR.py
drivers/FileSR.py
drivers/NFSSR.py
drivers/SMBSR.py

Signed-off-by: Thomas Mckelvey <thomas.mckelvey@citrix.com>

CP-28924: Declare thin provisioning capability for file based SRs

---

Makefile

Remove obsolete 39-multipath.rules file from install rules

---

drivers/lvutil.py

In the upstream lvm2 (v2_02_177), it handles duplicate PVs differently
with currently used lvm2(v2_02_130) in XenSever. It will prefer first PV
but before it will choose last PV it sees. For example:
root@xrtuk-13-09 ~]# ll /dev/disk/by-id/scsi-3600a098038303973743f486833396d42
lrwxrwxrwx 1 root root 10 Aug 27 08:51 /dev/disk/by-id/scsi-3600a098038303973743f486833396d42 -> ../../sdak
From the log:
SM: [12939]   WARNING: PV Iyrwu7-JpT6-l8dX-9K8x-Rz2z-n9hV-SUzMf9 on /dev/sdak was already found on /dev/sdd
So it the device will excluded by a filter internally.
There may be two options we can try to fix this issu:
1: Patch upstream lvm2 to let it use last seen PV, but from the
trend of upstream, it will prefer to use first seen PV and lots of
code related with change. So it will need lots of …

CA-294319: Do not create PV on first device

---

drivers/NFSSR.py
drivers/blktap2.py
drivers/nfs.py
tests/test_NFSSR.py

Keep the NFS timeo mount option in deciseconds always. Various parts of
the code appear to have tried to have it in seconds, except for one
place which apparently thought it was in centiseconds. This
inconsistency resulted in a timeout/retrans combination of 1000
deciseconds and 12 retries, which would mean it would take over 1.5
hours for an NFS operation to fail. This hides failures in the NFS
layer.
Adjust everywhere know that the timeo value is in deciseconds. Also,
since tapdisk will retry EIO, it makes sense to make the retry period
shorter and not to try so many times, so lower the defaults.

CA-299722 Adjust timeout and retrans NFS mount options

---

Makefile
scripts/usb_change
systemd/usb-scan.service
systemd/usb-scan.socket

udev does not tolerate the time it can take for XAPI to complete a
pUSB rescan request. Use a service listening on a socket to perform
the scan request so that the udev action just becomes writing to a
non-blocking pipe.

CA-286144: add usb-scan systemd units

---

drivers/nfs.py
tests/test_NFSSR.py

5 deciseconds and 5 retransmissions is too short for the default NFS
timeouts. Increase this to 100 deciseconds and 3 retransmissions. This
is sized so we we will get EIO after 100 seconds which is intended to
provide an indication that NFS is in trouble before we get a timeout
from other parts of the system.

CA-302514 increase default NFS timeouts

---

Makefile
drivers/FileSR.py
drivers/VDI.py
drivers/blktap2.py
drivers/plugins/__init__.py
drivers/plugins/keymanagerutil.py
drivers/vhdutil.py

I've rewritten the history a bit to halve the number of commits.

Merge feature/REQ-718 branch

---

drivers/blktap2.py

There are two reasons for this change:
- For some cases, there can be no host tags present. E.g. on directly attached
HA statfile, or some accidental failure when adding the tags.
- remove_tags is called at the end of VDI detach, which is to cease, rather
than to start, destructive operations. Even if the host tag is not present
for some reason, simply ignoring this and going ahead won't make the
situation worse. If there was damage, it was done already (at the time of
attching and onwards). Simply aborting at this point will probably make
things messier.
Signed-off-by: Zheng Li <zheng.li3@citrix.com>

CA-298641: be more benign on removing host tag

---

drivers/FileSR.py
drivers/vhdutil.py

The current "vhd-util scan" command makes use of the "-c" (NOFAIL) flag, so
that if it has difficulties scanning a particular VHD image file, it will
simply skip it, and the command always returns success. In a stressed
environment (e.g. CPU high load or poor connection to the storage), it might
return a partial list without giving any warnings.
With this change, we try without the NOFAIL flag first. If it fails, we
continue trying (ioretry). If it continues to fail, we'll log the result and
then go with the NOFAIL flag as the last resort, which should always succeed
(as before), but we'll additionally log its output in this case.
In addition, we improve logging in two places. If a line from the output of
"vhd-util scan" fails to parse, we'll log the line instead of ignoring it. For …

CA-273708: improve VHD scan for file-based SR

---

drivers/blktap2.py
drivers/util.py

With newer kernels, changing the scheduler in-kernel shortly after
device creation can deadlock. Instead, have SM set the scheduler. This
kind of policy decision is better kept in userspace anyway.
Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>

CA-312608: Set scheduler to noop for tdX devices

---

systemd/mpathcount.service
systemd/usb-scan.service

Since these are kicked by a pipe, explicitly prevent systemd from
putting their stdout and stderr on the same pipe so that they can't kick
themselves.

CA-314717 Explicit stdout and stderr for scan services

---

drivers/lvutil.py

CBT code make many checks for the existence of the cbtlog volume but if CBT is not enabled this logs exceptions when the volume is not found. Use doexec directly and check if the return code is 0 or not.

Avoid getting exceptions logged from checking if an lv exists

---

drivers/cleanup.py

To avoid SR contents changing during scan

CA-314822: use scanLocked in should_prempt

---

drivers/cleanup.py
drivers/lock.py

Also ensure lock objects are reset on forking the GC.

CA-324815: lock the SR in GC before deleting orphans.

---

drivers/cleanup.py

This caused XSI-474 and other reported customer issues.

CA-327382: reap child processes

---

drivers/util.py

This expunges the correct entries in the log, see job id 2701468.
This has not been through a BST yet.
Racked up some technical debt here, with no unit tests, will add these later.

CA-329841 - Sanitise chaps incoming usage

---

systemd/mpathcount.service
systemd/mpathcount.socket
systemd/usb-scan.service
systemd/usb-scan.socket

ExcecPostStart needs to be in the socket files not the service files, only the sockets are
auto-enabled,

CP-32433: kick the multipath and usb scanners at start

---

drivers/cleanup.py
tests/test_cleanup.py

This needs some extra integration testing, as i'm nervous of the effects.
To date this has been through the gcLVM and gcEXT no problems, I have also provoked a leaf coalesce manually and observed the creation of the speed log file, present and correct.
There is also the question of the persistence of the speed log, do we want it to persist after a reboot? Also do we want to clean it up during SR forget?

CP-32204: Dynamic limits to leaf coalesce using storage speed estimate.

---

drivers/cleanup.py
tests/test_cleanup.py

Defensive coding, in case the speedlog is overwritten with junk.

CA-332806 - Fix type mismatch when processing speed file

---

Makefile
scripts/storage-init
systemd/storage-init.service

Move the storage firstboot scripts out of xenserver-firstboot and
consolidate them into a single service that runs once during firstboot.

CP-31089: Move storage firstboot scripts out of xenserver-firstboot

---

drivers/XE_SR_ERRORCODES.xml

Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>

Fix xe-mount-iso-sr command name in error message

---

udev/65-multipath.rules

It seems that whilst in a large majority of cases a device add event
will also have all the kernel mulitpath data setup it sometimes doesn't
and we need to look at the data when we get a subsequent device change
event.
In order to not trigger the count script unneccessarily we
* Read the CH_MULTIPATH value from the udev data, this can only have
been set by a previous device add/change. If this is set and we are
removing the device we need to count. If it is set for any other
event, then we have already performed a path count so skip to end.
* If a device add/change event is received, check the DM table to
see if this is a multipath device. If it is then set the CH_MULTIPATH
variable and count.

CA-332890: evaluate multipath on device change as well as add.

---

drivers/blktap2.py
tests/test_blktap2.py

This should fix the issues.
It's been through a BVT (2817879) but not a BST due to Koji build issues.

CA-335178: Fix unitialized variable

---

drivers/devscan.py

since USB storage is already managed by udev SM

Filter out USB storage from HBA device

---

drivers/VDI.py

This has a use before definition error in it anyway so can never
have been used and SonarQube marks this as a blocking issue.

CA-337772: remove dead code handling qcow files.

---

scripts/storage-init

We encountered an issue where storage-init was syncing the DB
during an upgrade, so we revert to the behaviour of the 'old'
firstboot scripts.
(This PR is a sibling of https://github.com/xapi-project/xen-api/pull/4114)

CA-339329 firstboot scripts shouldn't sync DB when upgrading

---

tests/test_HBASR.py
tests/test_LVHDoHBASR.py

Unit tests for poorly covered HBA srs.

CP-33629 - Unit tests for HBA

---

scripts/set-iscsi-initiator

It appears that the directory structure for the set-iscsi-initiator script
was missing. The directory /var/lock/sm/iscsiadm was created.
Signed-off-by: Gheorghe Burac <gheorghe.burac@citrix.com>

CA-333441 create directory for set-iscsi-initiator

---

scripts/set-iscsi-initiator

CA-346583: make set-iscsi-initiator idempotent

---

drivers/cleanup.py

CP-35367: report GC progress by task

---

scripts/set-iscsi-initiator

The installer might not set alias and so iSCSIBoot can fail.

CA-349188: only the initiatorname is critical

---

drivers/blktap2.py

CA-349457: include the VDI uuid in the log when removing activating flag

---

drivers/02-vhdcleanup

This partially reverts back to old behaviour but with FCoE support added and extraneous sr scan removed.

CA-350437: simplify 02vhd-cleanup to only handle LVM refcounts

---

drivers/EXTSR.py
drivers/LVHDSR.py
drivers/LVHDoFCoESR.py
drivers/LVHDoHBASR.py
drivers/LVHDoISCSISR.py
drivers/OCFSoHBASR.py
drivers/OCFSoISCSISR.py
drivers/SR.py
drivers/mpath_dmp.py
drivers/util.py
tests/test_SR.py
tests/test_mpath_dmp.py

This commit increases performance by.
1) Reducing expensive calls to _pathfresh
2) Use multipath with option "-l" and then falling back to using the more expensive "-ll"
only if first operation it fails.
3) Add missing vdi_epoch operations to vdi operation list
This has been through a BST.

XSI-915: Improve performance of LVHDoHBA operations by

---

drivers/cleanup.py
tests/test_cleanup.py

CA-355289: ensure xapi is initialised before starting GC

---

drivers/tapdisk-pause

This has to be dead as it references the non-existant self variable
in a global context. There is an almost identical copy of the
method inside the Tapdisk class as an instance method which can use
self.

Remove dead code from tapdisk-pause

---

drivers/nfs.py
tests/test_nfs.py

Signed-off-by: BenjiReis <benjamin.reis@vates.fr>
Solves: https://github.com/xapi-project/sm/issues/511
As detailed in the issue, some devices (mostly QNAS devices) do not provide with NFS ACLs in `showmount -e` return, in this case we need to assume everyone is accepted, therefore `access = "*"`.

If no NFS ACLs provided, assume everyone

---

drivers/cleanup.py

Python runtime converts use of == to a call to "__eq__" on the object
and this is not implemented by the Xapi session XMLRPC proxy. After
https://github.com/xapi-project/xen-api/pull/4464 this code causes an
exception.

CA-356645: use "self.session is None" not "self.session == None"

---

drivers/cleanup.py

Extend allowed wait in garbage collector for VDI activating.

CA-356761: ensure that children are always reloaded on relink

---

udev/58-xapi.rules
udev/65-multipath.rules

Details explained in commit messages: udev is launching various commands when xvd* devices are plugged into Dom0 and this prevents unplug with a device in use error. Plug/unplug is needed for VDI import to work.
Tested with a storage driver domain, and also added some cleanups for td/nbd (there were udev rules to ignore these devices, but not everywhere, e.g. I was still getting some multipath commands launched for them).
Still need to test the td/nbd side of changes, hence the draft PR.

CA-334762/CA-356983: fix VDI import for storage driver domains

---

drivers/LVHDoHBASR.py
tests/test_LVHDoHBASR.py

If this is not done, in particular with a Fibre Channel SR where
the LUN mapping may be subsequently removed kernel errors can be
encnountered until the host is rebooted if another HBA SR is
scanned.
e.g.
Mar 23 13:43:10 <host> kernel: [446324.856765] sd 1:0:2:0: [sdd] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Mar 23 13:43:10 <host> kernel: [446324.856775] sd 1:0:2:0: [sdd] tag#0 Sense Key : Illegal Request [current]
Mar 23 13:43:10 <host> kernel: [446324.856778] sd 1:0:2:0: [sdd] tag#0 Add. Sense: Logical unit not supported
Mar 23 13:43:10 <host> kernel: [446324.856784] sd 1:0:2:0: [sdd] tag#0 CDB: Read(10) 28 00 00 00 00 00 00 00 80 00
If the host is rebooted between the SR being deleted and the LUN
mapping being removed then this error will recur until the host
is …

CA-352880: when deleting an HBA SR remove the kernel devices

---

drivers/util.py

Negative process exit codes indicate that the process terminated
with a signal so report these separately.

CA-327302: report signals in CommandException

---

drivers/nfs.py
tests/test_nfs.py

Setting nfsversion=4 uses either 4.0 or 4.1, depending what is
available.
It is already possible to explicitly force 4.1, add similar support for
4.0.
Explicitly choosing 4.0 can be important when trying to
diagnose potential performance regressions due to NFS versions / NFS
server changes.
Signed-off-by: Edwin Török <edvin.torok@citrix.com>

CP-38283: Support explicit NFS 4.0 version choice

---

drivers/cleanup.py
drivers/util.py
tests/test_cleanup.py

Parent returned from vhdutil.getParent is the path of the parent not a
VDI object. Lookup the VDI before dereferencing the raw attribute. Add
fault injection fist point to allow for testing.

CA-359621: fix regression in error handler

---

dev_requirements.txt
drivers/cleanup.py

This reduces the chances of failures due to the system clock changing,
for instance by NTP/chronyd moving the system time to sync to the server.

CP-38670: use monotonic time instead of time.time()

---

multipath/multipath.conf

Hello,
I found an incorrect QNAP entry in multipath.conf.
The product attribute was "iSCSI_Storage", but the actual QNAP product attribute was "iSCSI Storage". Underscores should be spaces.
I suggested writing 2 blocks of underscore and space in the forum below.
Please check the forum below for details.
https://xcp-ng.org/forum/topic/5194/multipath-conf-is-incorrect
I was suggested by forum users to give feedback to the fork source.
I use multipathing with iSCSI in QNAP.
Because of the different multipath speeds, I had to set a fixed priority.
I noticed this mistake with the multipath -ll command and posted.

QNAP product attribute is incorrect

---

drivers/util.py

Ensure alarm is correctly reset in case of success after user function execution.
Otherwise the SIGALRM signal can be emitted after the execution of the given function.

Fix timeout_call function

---

drivers/NFSSR.py
tests/test_NFSSR.py

CA-365359: cope with on_slave.is_open passing server=None

---

drivers/ISOSR.py
drivers/nfs.py

During creation of ISOSR with NFS params, we can get a generic error with this command line:
```
xe sr-create host-uuid=<uuid> content-type=iso type=iso name-label=<loc> device-config:location=<invalid_server_path>
```
Before this patch the returned error was:
```
Error code: SR_BACKEND_FAILURE_1200
Error parameters: , ,
```
After:
```
Error code: SR_BACKEND_FAILURE_222
Error parameters: , Could not mount the directory specified in Device Configuration [opterr=mount failed with return code 32],
```
Signed-off-by: Ronan Abhamon <ronan.abhamon@vates.fr>

Raise explicit error in case of NFS mount failure

---

drivers/blktap2.py
tests/test_blktap2.py

In XSI-620 the storage manager scripts were blocked by a tapdisk
process which was hung totally and blocked for over an hour. A
timout was added to this close operation to unblock things but the
timeout is only on the IPC and so breaks the IPC link if the timeout
is reached. Which is fine if the remote process is entirely wedged,
however when a close is requested and there are pending IO requests,
possibly during a migrate, the close operation can take significantly
longer than the currently permitted 30 seconds, 50 seconds observed
in failing tests. So, extend the timeout such that this scenario
should be handled successfully whilst not reintroducing the issues
seen in XSI-620.

CA-368769: extend the timeout on tap-ctl close

---

drivers/SR.py

If
```
xe host-param-set multipathing=true uuid=<uuid>
```
is used it doesn't set the multipathhandle (which XenCenter does do), but as we only support Device Mapper Multipath mutipathing now we can set that as a default if multipathing is enabled in this way.
This doesn't change the other path of reading from `dconf` which is a deprecated mechanism anyway as that requires `multipathhandle` to be supplied in order to activate the path.

CA-369395: default multipath handle to dmp if not set

---

drivers/NFSSR.py
drivers/nfs.py
tests/test_NFSSR.py
tests/test_nfs.py

If an error is thrown from get_supported_nfs_versions the error path mishandles the error and ends up in the catch all error handling having also dropped all the original error context so that the logs are useless. Fix this and cover the code paths with unit tests.

CA 370037: Fix error handling in NFS SR Create

---

multipath/multipath.conf

Hi all,
we are using some Dell ME4 iSCSI-NAS Devices. Would be great to have a good multipath-config in place by default. For details: see https://downloads.dell.com/manuals/common/powervault-me4-series-linux-3924-bp-l_en-us.pdf
Regards,
Ulrich Göttlich

Added Dell ME4 multipath config

---

.github/workflows/main.yml
dev_requirements.txt
tests/run_python_unittests.sh

* shellcheck
* direct check result of coverage for test code
* use native pyhon unit test runner not nosetests
* remove virtual env start as it's not terribly useful on modern OSes (until Python 3 happens)

Tidy the unit test runner script

---

drivers/EXTSR.py
drivers/LVHDSR.py
drivers/NFSSR.py
drivers/SR.py
tests/test_SR.py

If a device does not exist, then this is a separate error. If it does, then by definition its path is a valid one so the check is unnecessary and serves only to cause problems when new device has some unexpected (but valid) character in its name.
Likewise whether or not an NFS server path string is valid is the business of that NFS server, not the client code which is attempting to mount it.
Because checkroot() is removed (it has no remaining purpose), some subclasses of the SR class need to be modified as they relied on a side-effect of it being called.

CA-370696 Do not attempt to validate device or NFS server paths

---

drivers/NFSSR.py
drivers/util.py
tests/test_utils.py

- Use `getaddrinfo` on `dconf['server']`
Signed-off-by: BenjiReis <benjamin.reis@vates.fr>

Resolve hostname to determine which transport to use

---

README.md

Signed-off-by: Samuel Verschelde <stormi-xcp@ylix.fr>
Not the most important PR for this project, but once you've seen the typo it can't be unseen, so I had to do it :)

Fix spelling of "XenServer" in README.md

---

multipath/multipath.conf

The file has evolved over years with a mix of spaces and tabs. Make it more consistent.
Signed-off-by: Samuel Verschelde <stormi-xcp@ylix.fr>
I opted for spaces and aligning the right values vertically. Other choices are possible.

Harmonize indentation in multipath.conf

---

mk/sm.spec.in

Unless I have misunderstood the history of the sm and lvm2 packages, this uninstall code comes from previous times when the sm spec file itself contained more changes to the lvm2 configuration, changes that I think I have now seen in XS's lvm2 spec file (the creation of /etc/lvm/master/lvm.conf, for example).
I don't expect people to uninstall the sm package, but if I have not made a mistake, this is probably cleaner.

mk/sm.spec.in: remove uninstall operations now unrelated to this package

---

drivers/ISOSR.py
drivers/blktap2.py
drivers/mpath_cli.py
drivers/scsiutil.py
drivers/wwid_conf.py
tests/test_ISOSR.py

Running tests would show such warnings:
```
tests/test_ISOSR.py:201
/data/src/sm/tests/test_ISOSR.py:201: DeprecationWarning: invalid escape sequence \j
username='citrix\jsmith',
drivers/ISOSR.py:59
/data/src/sm/drivers/ISOSR.py:59: DeprecationWarning: invalid escape sequence \.
regex = re.compile("\.iso$|\.img$", re.I)
```

Fix under-quoted backslashes by using raw strings

---

drivers/LVHDoISCSISR.py

Make iSCSI multi session robust to discovery failures as well as login failures. Some of the sessions are permitted to fail so long as at least one successfully connects.

CA-375968: multi session iSCSI updates

---

drivers/udevSR.py

This PR should properly allow for SM attach to use self.path when VDI.attach is called, but in case the drive /dev/ device name changes, on SM start, it should load the vdi and get the new VDI path linked by the symlink.
Edit : I haven't done extensive testing with unplugging drives and swapping SATA ports, but a SR scan is working as expected, and attaching drives is working correctly with symlinks to /dev/disk/by-id/ devices.
Commands used to test:
```
mkdir /srv/pass_drives/
cd /srv/pass_drives/
ln -s /dev/disk/by-id/ata-WDC_WD120EFBX-68B0EN0_5QKP16YB
ln -s /dev/disk/by-id/ata-WDC_WD120EFBX-68B0EN0_5QKT00MB
ln -s /dev/disk/by-id/ata-WDC_WD120EFBX-68B0EN0_5QKT9B9B
xe sr-create name-label=Pass_Drives type=udev content-type=disk device-config:location=/srv/pass_drives
```
This patch only …

Allow for udev symlink following

---

drivers/BaseISCSI.py
drivers/LUNperVDI.py
drivers/SR.py
drivers/blktap2.py
drivers/util.py

noop and cfq scheduler are dropped by 6.x linux kernel, to keep compatibility with 4.x linux kernel, following fallback is setup
* none -> noop
* bfq -> cfq

CP-42222: Handle blk-mq noop and cfs schedulers

---

drivers/mpath_dmp.py

Test failures have been seen when after successfully detecting and listing the non-multipath device, e.g.
```
SSH root@xx.xx.xx.xx readlink -f /dev/disk/by-id/scsi-3600a098038313577792450384a4a6857
/dev/sdm 
```
the test then fails when waiting for the multipath device to appear after enabling multipath. The failure is very hard to reproduce on demand and multiple (20+) runs can succeed and then a single failure will be seen somewhere else. Best guess is that sometimes it takes a bit longer for the device to settle so extend the timeout. If this doesn't address the issue it may require some interaction with `systemd-udevd`

CA-374612: extend wait for multipath device arrival to 30 seconds

---

drivers/FileSR.py

The error code itself is short-lived and not used, but the "524" string is checked in various tests, so sync accordingly.
I admit I'm puzzled by the fact this check only happens when a "fist point" is active, I would have thought this check for hardlink support would be more generally useful than that?

FileSR: fix error code

---

drivers/EXTSR.py
drivers/FileSR.py
drivers/NFSSR.py
drivers/SMBSR.py

The loadLocked parameter to .vdi() methods only hides duplicated code paths, so it appears we can get rid of it.

Get rid of vdi loadLocked parameter

---

drivers/EXTSR.py

Parentheses and brackets makes explicit line continuations unnecessary.

EXTSR: get rid of superfluous explicit line continuations

---

drivers/mpath_dmp.py

Previous change in 65a6fa1 was incomplete and didn't fully address the issue as we also see failures in the previous wait_for_path.

CA-379434: extend wait for multipath to 30 seconds

---

Makefile
drivers/BaseISCSI.py
drivers/LVHDoISCSISR.py
drivers/SR.py
drivers/sr_health_check.py
systemd/sr_health_check.service
systemd/sr_health_check.timer
tests/test_LVHDoISCSISR.py
tests/test_sr_health_check.py

If, when an iSCSI SR is attached, some of the paths are not reachable they will not be subsequently connected should the connectivity issues be resolved, without detaching the SR or rebooting the host. Neither of these options give a good experience for users of the software. Add a systemd timer which will, periodically (default 10 minutes), ask each SR to do SR specific "health" checks. Currently only a checker for the iSCSI sessions is present but more can be added to this pattern in the future as needs arise.

CA-379329: check for missing iSCSI sessions and reconnect

---

drivers/ISOSR.py
tests/test_ISOSR.py
tests/test_testlib.py
tests/testlib.py

This change fixes `raise util.CommandException` not passing in enough arguments and throwing an unexpected `TypeError` inside `mountOverSMB`. The exception has been replaced with `XenError`. [b7eea5d2452]
A unit test was added to cover this code path.
A new method `get_error_code` was added to `testlib` to retrieve error codes from error names by parsing `XE_SR_ERRORCODES.xml` e.g. `get_error_code("SMBMount")` => `111`. This is to avoid hardcoding the error codes as magic numbers in the test. [db0c877b595]
New `testlib` unit tests added for new `get_error_code` method because build will fail without 100% coverage on test files. [ca4e932ef31]
The code change and an early version of the unit test were ran through Storage: BST (run 187746).

CA-282738: fix bad exception thrown in mountOverSMB

---

scripts/storage-init

If a user creates their own Local Storage manually before XenServer first
boots then sm/scripts/storage-init will delete it and try to create another
one leaving the volume groups in a messy unusable state. This bug can also be
replicated by simply calling storage-init again manually after XenServer has
already been installed.
This change modifies storage-init to not touch Local Storage if it already
exists.
This was tested by doing a new XenServer install and checking that the Local
Storage is created as normal. Then storage-init was called a second time
manually and confirmed the volume groups were not modified.

CA-372064: storage-init don't try to make Local storage if it already exists.

---

drivers/LVHDSR.py

When static vdis are used there is no snapshots and we don't want to call method from XAPI.

Fix vdi-ref when static vdis are used

---

drivers/cleanup.py
tests/test_cleanup.py

The GC can be started by an on attach SR scan and sometimes complains that the SR is, according to Xapi, not plugged on the host. When encountering this error pause and retry a few times before giving up.
```
> <hostname> SMGC: [<pid>] *~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*
> <hostname> SMGC: [<pid>]          ***********************
> <hostname> SMGC: [<pid>]          *  E X C E P T I O N  *
> <hostname> SMGC: [<pid>]          ***********************<
> <hostname> SMGC: [<pid>] gc: EXCEPTION <class 'util.SMException'>, SR <uuid> not attached on this host
> <hostname> SMGC: [<pid>]   File "/opt/xensource/sm/cleanup.py", line 3174, in gc
> <hostname> SMGC: [<pid>]     _gc(None, srUuid, dryRun)
> <hostname> SMGC: [<pid>]   File "/opt/xensource/sm/cleanup.py", line 3049, in _gc
> …
```

CA-355289: if the SR is not plugged on GC startup wait a little while

---

multipath/multipath.conf

Added support for HP/HPE MSA storage appliances such as the HP MSA2050 and HPE MSA2060.
The added configuration settings were sourced from the following location: https://community.hpe.com/t5/msa-storage/msa-2060-sas-red-hat-8-multipathing/td-p/7163998 As well as my own experience, here:
https://xcp-ng.org/forum/topic/6553/can-t-create-sr-on-fibre-channel-storage-msa2062-sr_backend_failure_53/

Update multipath.conf with support for HP/HPE MSA storage appliances

---

drivers/XE_SR_ERRORCODES.xml
drivers/fjournaler.py
drivers/journaler.py
drivers/util.py
tests/test_fjournaler.py

Rather than allow JournalerExceptions to propagate up and eventually turn into "unhandled" error 1200s, turn all instances into the appropriate type of LVM error code and reture the JournalerException class, at least from the LVM journaller

CA-379315 Use XE_SR_ERRORCODES in the LVM journaller

---

drivers/nfs.py
tests/test_ISOSR.py
tests/test_NFSSR.py

Newer kernels have more reliable NFS timeouts but they also do not behave quite like the manpage describes regarding major timeouts with soft TCP NFS mounts.
From experimentation and reading the code, a major timeout occurs after min(600, (timeo/10) * (retrans + 1)) seconds.
With the current defaults, that means 40 seconds. However, the intention with CA-302514 was to set it to 100 seconds so increase timeo and retrans accordingly.

CA-381221: Increase NFS timeouts to the expected value

---

drivers/NFSSR.py
drivers/nfs.py
tests/test_NFSSR.py
tests/test_nfs.py

NFSv4 only environments don't support `rpcinfo`
and `showmount` calls as they're missing NFSv3
services.
When `rpcinfo` or `showmount` fails, try to mount
NFSv4 pseudo FS '/' to add '4' to supported NFS versions
and run `ls` on the mounted pseudo FS to offer the first
folder level of exports.
See: https://github.com/xapi-project/sm/issues/551
And: https://github.com/xcp-ng/xcp/issues/135

Support NFSv4 only environment

---

drivers/ISOSR.py
tests/test_ISOSR.py

Have ISOSR check for NFS version compatibility as well the presence of a running server, when preparing to for an NFS ISO mount. Also, have this checking done prior to the creation of a mountpoint.

CA-339581: Report NFS version incompatibilities for ISO SRs

---

drivers/ISOSR.py
tests/test_ISOSR.py

Pre-mount checking of an NFS server was failing in the face of a ipv6 share location, as it didn't how to understand the form of the location string. The logic of parsing NFS location strings has now been unified, to avoid this problem.

CA-339581 Unbreak NFS ipv6 support in ISOSR

---

drivers/SRCommand.py
drivers/journaler.py
drivers/srmetadata.py
drivers/util.py
tests/test_SRCommand.py
tests/test_srmetadata.py
tests/test_util.py
tests/testlib.py

CA-379287 is a problem parsing XMLRPC requests that contained non-ascii characters, due to the way the body of a request would be passed on the command line, and then decoded to appear in `sys.argv`,
CP-383791 is an issue that is easier to provoke with CA-379287 fixed (which is why I'm putting them in the same PR): if there is a VDI in an LVM SR that has non-ascii characters in its name label, `LVMMetadataHandler` can no longer read the corresponding MGT file, at the code's implicit assumption that byte offsets and character offsets are the same thing. Before fixing that, I wanted to get better unit test coverage for the code in question, and clear out some cruft that was making the code harder to follow.

CA-379287 and CP-383791: non-ascii VDI names 

---

drivers/blktap2.py

To allow for depriviling pygrub the /dev/sm/backend/ devices need to have group ownership for the disk group and for the group to be granted read-only access to the device.

CP-45514: set ownership and permissions on backend

---

drivers/EXTSR.py
drivers/FileSR.py
tests/test_FileSR.py

FileSR.attach modified to change the mount point permissions to 700.
This prevents any non-root user from reading the contents of the SR.
EXTSR.attach modified to call FileSR.attach.
Other SRs could be changed to reuse FileSR.attach in the future.
Unit tests added for FileSR to test old and new attach functionality.
XenRT test in different PR.

CA-371791: Fix world readable permissions on EXTSR

---

drivers/ISOSR.py
tests/test_ISOSR.py
tests/testlib.py

* Use os.listdir rather than util.listdir for finding images in an SMB share. I don't really know why the latter exists, but I didn't want to get side-tracked by the question of whether it could be eliminated or (if not) how it should best handle non-ascii characters in filenames - especially as I doubt that's ever an issue outside of ISOSR.py.
* Refactor the identification of images so that finding and filtering are in a single function.
* When looking for image files in a mounted directory, ignore ones with problematic names. This covers non-utf-8 names (which will always be a problem, but that aren't likely to occur in this context), and names that have had their utf-8 encodings mangled by Python's filesystem encodings (which I'm anticipating will stop being a problem with Python 3.7 …

CA-384030 Ignore awkardly named images in ISO SRs

---

multipath/multipath.conf

From Dell's doc - https://i.dell.com/sites/csdocuments/Shared-Content_data-Sheets_Documents/ar/dz/ESG-TechWP-EQL-MultipathIOwithCitrixXenServer.pdf
```
Note: There is a known issue with Linux multipathing daemon (multipathd) versions built from source 
prior to May 2011 when using path_checker readsector0 in the devices section of the 
multipath.conf file. Using this value will cause iSCSI protocol errors when used with Dell EqualLogic PS 
Series Firmware v7.x. This issue does not exist with versions of Dell EqualLogic PS Series Firmware prior 
to Version 7.0. Upgrading to Dell EqualLogic PS Series Firmware Version 7.x with path_checker 
readsector0 set will result in total connectivity loss.
```

CP-45927: set multipath checker for Equalogic 100E-00 to tur

---

drivers/nfs.py
tests/test_nfs.py

Just because the rpcinfo list obtained from rpcbind does not contain NFS4 does not mean it is not supported. Probe for it if it is not in the list. Some filers supporting both do not register NFS4 with rpcbind.

CA-384783 Probe for NFS4 when rpcinfo does not include it

---

drivers/util.py

Only log errors if all attempts to set the block device elevator scheduler fail, to reduce noise in the logs which look like errors and are not.

CP-46807: reduce logs from scheduler set errors

---

drivers/FileSR.py
tests/test_FileSR.py

We can get a trace like that if the SR is not attached:
```
2170:Oct 10 16:02:59 xcp4 SM: [2564] ***** NFSFileVDI.attach_from_config: EXCEPTION <type 'exceptions.AttributeError'>, 'NoneType' object has no attribute 'xenapi'
2329-Oct 10 16:02:59 xcp4 SM: [2564]   File "/opt/xensource/sm/NFSSR", line 296, in attach_from_config
2427-Oct 10 16:02:59 xcp4 SM: [2564]     self.sr.attach(sr_uuid)
2487-Oct 10 16:02:59 xcp4 SM: [2564]   File "/opt/xensource/sm/NFSSR", line 148, in attach
2573-Oct 10 16:02:59 xcp4 SM: [2564]     self._check_hardlinks()
2633-Oct 10 16:02:59 xcp4 SM: [2564]   File "/opt/xensource/sm/FileSR.py", line 1122, in _check_hardlinks
2734-Oct 10 16:02:59 xcp4 SM: [2564]     self.session.xenapi.SR.remove_from_sm_config(
2816-Oct 10 16:02:59 xcp4 SM: [2564]
```
Because the …

fix(NFSSR): ensure we can attach SR during attach_from_config call

---

Makefile
drivers/LVHDSR.py
drivers/lock.py
drivers/lock_queue.py
drivers/lvutil.py
mk/sm.spec.in
tests/test_LVHDSR.py
tests/test_LVHDoHBASR.py
tests/test_LVHDoISCSISR.py
tests/test_SRCommand.py
tests/test_lock_queue.py
tests/test_lvutil.py

This is intended to prevent a storm of later LVM commands from usurping the lock that an earlier command is waiting for, just because they happened to manage to start waiting before the original holder was done.
In some pathalogical circumstances, this has been known to result in a commant taking many minutes to get the lock.

CP-39600: Rework LVM locking to use fair lock queue

---

drivers/ISOSR.py
drivers/nfs.py

See https://github.com/xapi-project/sm/blob/master/drivers/ISOSR.py#L318-L326 
Valid values for type are `cifs` or `nfs_iso`. That is not very consistent but the built-in docs should reflect reality, the code can be extended later to support more consistent naming.

fix(ISOSR): type accepts 'nfs_iso' not 'nfs' as the docs claim

---

drivers/ISOSR.py
tests/test_ISOSR.py

ISOSR falling over when no username is given is a regression that looks to have been introduced in commit
cbd7226b012d145b52ef50c45c69987d4050b12a when the use of a credentials file was removed.
The ISOSR unit tests were already covered cases of not having credentials - as evinced by having "guest" in the expected mount options. However, they were doing this in a rather confused way that hid the bug by supplying a username regardless. Now only the credentials tests do this.

CA-386281 CIFS username can be omitted in ISO SR

---

drivers/mpathcount.py
systemd/mpathcount.service
tests/test_mpathcount.py

- Save the multi-path status to a regular file whenever a Udev event is triggered.
- Generate the 'mp_status' file if it does not exist when starting the 'mpathcount' service for the first time.

CP-46863 Dump Multipath Status from Storage Manager

---

drivers/lock_queue.py

This was breaking storage-init as it goes back into the XML stream to the toolstack and causes an XML parse failure.

CP-39600: remove stray print call

---

drivers/LVHDSR.py

This was resulting in a deadlock condition being detected and is no longer required after the chnages for CP-39600 in 125aa9e.

CA-385069: Remove unnecessary LvmContext wrap

---

drivers/FileSR.py
drivers/NFSSR.py
drivers/SMBSR.py
drivers/XE_SR_ERRORCODES.xml
tests/test_FileSR.py
tests/test_NFSSR.py
tests/test_SMBSR.py

This deals with the situation where an NFSSR or SMBSR is being attached, but that share it uses cannot be written to.
* Make an explicit check that the share can be written to after it is mounted, raising a suitable error message if it's not. The check comes before the hard-link check, as this also writes to the share, and so would fail in this situation.
* If the attach fails (for this, or any other, reason) after the share has been mounted, ensure that it's unmounted. This is because if it is left mounted then a subsequent attach may succeed, by virtue of the checks being skipped.

CA-387770 Improve error message for readonly shares

---

drivers/blktap2.py

During VDI activation in the blktap module and in case of failure in "sm.VDI.from_uuid" call, the RO/RW tag is never removed. As a result a VDI can no longer be used correctly: an assert is triggered each time we try to re-activate this volume because the tag is still present.

Always remove the RO/RW tag from VDIs in case of failure

---

drivers/cleanup.py
tests/test_cleanup.py

The problem showed up with NFSSR, but other SR types work the same way: the detach method was causing any active GC for an SR to abort, before going on to the rest of work of detaching; but there was nothing preventing a new GC starting in between. The change is to prevent the GC lock for an SR being acquired (as the GC need to do in order to become active) whilst something else (such as an sr_detach operation) is holding the SR lock; and (in case the GC does this just after the SR has been detached) it avoids doing anything if the SR is no longer plugged in.
It might have been sufficient to guard the acquisition of the GC lock like this in _gcLoop, but I decided to wrap the GC lock so that any acquisition of it requires the SR lock momentarily be acquired.

CA-386316 Fix race condition between sr_detach and GC

---

drivers/NFSSR.py
drivers/SMBSR.py
tests/test_NFSSR.py
tests/test_SMBSR.py

Completing CA-387770 to check for read-only remote filesystem at SR creation time as well as attach.

CA-387770: check for read-only shared fs at create

---

tests/test_on_slave.py

*args and **kwargs must be forwarded to __import__ otherwise the import context (global & local) can be incomplete to find local paths of external modules. In this situation, "ValueError: Empty module name" is thrown.

Implement correctly fake_import in test_on_slave.py

---

Makefile
drivers/SMBSR.py
drivers/srmetadata.py

This is a first quick pass on errors raised by pylint 2.16.4. Nothing critical, mostly cleanups that also improve readability (and as a side effect can help in the future to enable type checking).
The goal is to make #605 mergeable - we're not there yet, but a few similar fixes should do.

Pylint fixes

---

drivers/cleanup.py
tests/test_cleanup.py

Commit b7b90c80614a0878526543ac35ee03653064f0f0 was addresing a race condition between the Garbage Collector and the SR detach operation where the GC could get started while the SR detach was proceeding due to there not being any mutual exclusion between these operations. To address this the code was changed to obtain the gc_active lock only when within the SR lock, which is also held by the detach operation. This prevents the starting GC process from acquiring the active lock until the detach has completed, at which point the SR would be detached and the GC would exit.
There was a problem with this commit in that it used a Lock acquireNoblock to acquire the SR lock and if it failed to do so assumed that this meant the GC was already running. As the GC is typically kicked as the result of …

CA-388933: rework GC Active lock to ensure GC starts

---

drivers/blktap2.py

When this code was orginally added there was no default value for the nfs_timeout and so the timeout would only have been used if
1. The SR type was NFS
2. The SR had a overriden setting for nfs-timeout in the other-config
Since that time the calculation of the NFS client timeout has been changed considerably and is set with a balance between timeo and retrans values. In particular the get_nfs_timeout method will now always return a non-zero value.  This results in the SM always applying a request timeout to blktap of 50 seconds (unless the timeo value has been set in the SR device config), which is considerably lower than the default request timeout in blktap itself which is 120 seconds.
NFS protocol timeouts are also no longer considered to be retryable errors within blktap so tying the …

CA-390490: remove override of blktap request timeout

---

.github/workflows/main.yml
misc/fairlock/.gitignore
misc/fairlock/Makefile
misc/fairlock/fairlock.c
misc/fairlock/fairlock.py
misc/fairlock/fairlock@.service
mk/sm.spec.in
tests/run_python_unittests.sh
tests/test_fairlock.py

None of the file-based locking systems available are "fair", as in, there is no guarantee that the first waiter will not be usurped when the lock is released by later waiters, thus suffering from lock starvation. This has been something of a problem across various attempts to wrap access to LVM, and indeed it turns out that multipath commands also need to be serialised on some of the same resources.
This adds a small templated systemd service which does nothing but accept one connection at a time on a UNIX Domain socket, with a fairly long accept queue. The service is started when needed (thus every process using this mechanism needs permission to start the service), and the "Lock" is acquired by connecting to the socket. connect() on UNIX Domain sockets does not time out, and waiting …

CA-387861 Introduce fair locking subsystem

---

drivers/blktap2.py
tests/test_blktap2.py

The error handling for empty CD drive assumes a path containing '/dev/xapi/cd/' but the path has been resolved to the actual device before the open operation is attempted. Check for paths of the form '^/dev/sr' as well so that the correct error message is emitted.

CA-384942: path to the VM CD drive has been resolved to real device

---

Makefile
drivers/lvutil.py
drivers/mpath_cli.py
drivers/mpath_dmp.py
tests/test_LVHDSR.py
tests/test_LVHDoHBASR.py
tests/test_LVHDoISCSISR.py
tests/test_lvutil.py
tests/test_mpath_dmp.py

Wrap calls to commands which need to access the device mapper in a context manager for a resource called "device-mapper" so that they get serialised in a fair manner (no queue-jumping like a lockfile would have).

Make use of new fair locking subsystem

---

drivers/LVHDSR.py
drivers/util.py
tests/test_LVHDSR.py

Within the detach operation checks are made that none of the device mapper devices for the SR volume group have opern handles. The falls false if operations on other LVM srs happen to call a device mapper operation such as `lvs` or `vgs` at the point the check is made as these operations can result in all of the devices managed by the device mapper subsystem being accessed as part of the scan. this then gives a false response for the open file handles check.

CA-392823: ensure no device mapper conflicts in LVHDSR detach

---

drivers/LVHDSR.py
drivers/LVHDoISCSISR.py
drivers/SR.py
drivers/SRCommand.py
drivers/sr_health_check.py
drivers/xs_errors.py
tests/test_BaseISCSI.py
tests/test_FileSR.py
tests/test_HBASR.py
tests/test_ISOSR.py
tests/test_LVHDoFCoESR.py
tests/test_LVHDoHBASR.py
tests/test_LVHDoISCSISR.py
tests/test_NFSSR.py
tests/test_SMBSR.py
tests/test_SR.py
tests/test_SRCommand.py
tests/test_blktap2.py
tests/test_cbt.py
tests/test_mpath_dmp.py
tests/test_srmetadata.py
tests/test_testlib.py
tests/test_trim_util.py
tests/test_util.py
tests/test_vhdutil.py
tests/test_xs_errors.py
tests/testlib.py

xs_errors is one of the lowest level modules in the SM codebase yet it
imports the SR module, in order to access the SROSError class, which
is one of the highest level modules. The SR subclasses then import the
xs_errors module.
Correct this inverted dependency chain by moving the declaration of
the error class into xs_errors and fix up the usage.
Also load the XML error message declarations from a sibling file to 
simplify the unit tests and remove a hard coded path, which might
in the future change.

CP-49689: remove reverse dependency on SR from xs_errors 

---

drivers/FileSR.py
drivers/LVHDSR.py
drivers/cleanup.py
drivers/iscsilib.py
drivers/lock.py
drivers/resetvdis.py
tests/test_FileSR.py
tests/test_cleanup.py

In the process, rename LOCK_TYPE_RUNNING to LOCK_TYPE_GC_RUNNING to describe *what* is running when it's running. This matches LOCK_TYPE_GC_ACTIVE which remains in cleanup.py because it is only used there.
Rename the global variables in cleanup.py to describe *what* is Active/Running.

CP-49720 Move LOCK_TYPE_RUNNING from cleanup.py to lock.py

---

Makefile
drivers/FileSR.py
drivers/LVHDSR.py
drivers/cleanup.py
mk/sm.spec.in
systemd/SMGC@.service

Add a templated oneshot service and use systemctl to start it. The systemctl command is invoked with "--no-wait" so that it returns immediately because the "oneshot" nature of the service would otherwise wait until the command completes.
Note that because the service is a oneshot with RemainAfterExit=no (so we can multiply start it), it will go from "activating" to "dead" without ever appearing to be "running".

CP-49775 convert SMGC to systemd service

---

misc/fairlock/fairlock.c
misc/fairlock/fairlock.py

Log to LOCAL2 at log level INFO when a lock is acquired and released, and when the client holding the lock sends anything through the socket (they can use this to identify themselves to the logging e.g. by sending "PID <PID>"
Extended from Tim's original change to actually pass PID and (monotonic) time from the client.

Add logging to fairlock

---

drivers/lvutil.py
tests/test_lvutil.py

In lvmohba test, the test failed at
`SR.destroy(sr_ref) -> removeVG -> pvremove ` with the lvm error message "No devices to process".
The root cause is that the PV which was to be removed
was not really used as PV when it comes to multipathed devices. 
The LVM official document says:
"Since each LUN has multiple device nodes in /dev  that point to the same underlying data,
they all contain the same LVM metadata
and thus LVM commands will find the same metadata
multiple times and report them as duplicates.
These duplicate messages are only warnings
and do not mean the LVM operation has failed.
Rather, they are alerting the user that only one of the devices has been used as a physical volume and the others are being ignored."  
Please refer to …

CA-393194: Fix pvremove failure

---

multipath/multipath.conf

Hello All,
i used the HPE Storage Toolkit for Linux instructions to create this configuration.
We are actively using this config right now with our HPE Nimble AF-40 and 5 xcp-ng hosts.
https://infosight.hpe.com/InfoSight/media/cms/active/public/pubs_Linux_Integration_Guide_4_0_2.pdf

feat: add HPE Nimble multipath configuration

---

misc/fairlock/fairlock.c
misc/fairlock/fairlock.py
mk/sm.spec.in

Under some circumstances (when the listen queue is short enough) a process's blocking connect() to a UNIX-domain stream socket can return success even when the server side has not yet called accept().
To work around this, we have the server portion write a small fixed blob of data to each new connection and require the client to read it before it considers itself to have the lock; merely being connected successfully is no longer sufficient.

CA-395554 Improve fairlocking reliability

---

drivers/scsiutil.py

In case there is an issue during refresh_lun_size_by_SCSIid() which causes it to return False, log what the issue actually is so that some attempt can be made to address it. If retries need to be added, we need to know *what* needs to be retried.

CA-395560 Log exception details when LUN refresh fails

---

drivers/lvutil.py

In the extremely rare case that the LV is still in use when an attempt is made to deactivate it, it would be helpful to know what has it open.

CA-397084 Log any user of LV at deactivate

---

drivers/cleanup.py
tests/test_cleanup.py

1. On the first iteration do not assess any of the failure criteria
2. Allow for two "grace" iterations, where the size is permitted to grow and only consume those if the current size has grown more than permitted from minimum achieved.

CA-396124: amend criteria under which the garbage collector aborts

---

drivers/blktap2.py
mocks/XenAPI/__init__.py
tests/test_blktap2.py

It should be possible to activate a VDI on two different hosts in a pool simultaneously, provided read-only access is all that it required. So, if one host tries to activate in a brief window when another host has put the transient "activating" key on the VDI, it should be allowed to retry.

CA-398958 Cope with concurrent read-only activations

---

mk/sm.spec.in

Amend the fairlock upgrade scriptlet so that it uses full paths. This prevents it failing unexpectedly. Also, change it from a %posttrans scriptlet to a %post scriptlet so that the new version will have an effect immediately any new version is available.

CA-399643 Use full paths when stopping fairlock on upgrade

---

drivers/mpathcount.py
drivers/sr_health_check.py
tests/test_mpathcount.py
tests/test_sr_health_check.py

We had a flurry of these issues as fallout from an, independent, xapi startup issue. So handle the condition gracefully with a log entry and don't backtrace the exception

Add checks for Xapi enablement

---

Makefile
drivers/cleanup.py
mk/sm.spec.in
scripts/stop_all_gc
tests/test_cleanup.py

The intent being that before the toolstack restart operation actually stops xapi that this script will be called and stop all in-flight GC processes so that they don't try and make use of xapi services whilst it is restarting and potentially leave VMs in the paused state due to being unable to unpause them on a supporter node due to a lack of a local xapi process to forward the on-host plugin call.

CP-51658: install script to allow stopping all in-progress GC operations

---

drivers/FileSR.py

It appears that SMB3 filers or Windows hosts can return EACCES in response to a rename of a file over one of the links to a file if the rename is done too soon after the hardlink is made. Allow the rename to be retried in the event of EIO or ACCES.

CA-400743: perform post snapshot rename in ioretry

---

drivers/BaseISCSI.py

It's possible that a new LUN has been exported since we created the iSCSI session and we might not see it. Try to scan the iSCSI bus and see if the expected device appears.

CA-401068: if iSCSI device path is not found scan the bus

---

drivers/cleanup.py
tests/test_cleanup.py
tests/test_fairlock.py

Also fix an attribute error in a test flagged by static analysis

CP-42675: send messages to Xapi if GC has insufficient space 

---

.gitignore
misc/fairlock/fairlock.py
tests/test_fairlock.py

Cope with the case where the fairlock service is restarted while something is in the middle of connecting to it.

CA-400275 Tolerate a restarting fairlock service while connecting

---

drivers/SRCommand.py
drivers/VDI.py
drivers/trim_util.py
drivers/util.py

sr_get_capability can create, and subsequently log out a local Xapi session, however the users of the method will most likely already have an open session so allow that to be passed to avoid session churn in xapi.

CP-52844: allow for open session to be passed to sr_get_capability

---

drivers/SRCommand.py
drivers/XE_SR_ERRORCODES.xml
tests/test_SRCommand.py

It is possible that a XenAPI call to xapi will result in an xmlrpc ProtocolError being returned, typically a 500 Internal Error. As it is not practical to wrap all the calls to xapi via the xenapi session in a specific exception handler add one into the outer run method to ensure that it is converted to an error code and not an unknown error.

CP-52852: add handler for xmlrpc ProtocolError

---

drivers/cleanup.py
drivers/vhdutil.py
tests/test_cleanup.py
tests/test_vhdutil.py

The `VDI.canLiveCoalesce` method can manipulates sizes of different units because of this change:
```
CP-40871: use VHD allocation size in checking canLiveCoalesce
2f863b9fce6f2978499892d8c019bb3ab7ad72c5
```
As a result, the `canLiveCoalesce` method can return `True` and cause coalesce attempts
resulting in "Timed out" exceptions.
* Only drivers deriving from `FileSR` are impacted.
* The size of `self._sizeAllocated` is calculated correctly when `vhdutil.getAllocatedSize`
is called but there is a problematic case where `getVHDInfo` is used instead.
And this function does not convert `info.sizeAllocated` from block size to bytes.
* Additionally, the getter `getAllocatedSize` should retrieve the allocated size if it's equal to -1.
Otherwise `VDI.canLiveCoalesce` can compare -1 to a …

fix(cleanup.py): bad live coalesce check regarding FileSR

---

drivers/mpathcount.py
tests/test_mpathcount.py

The current implementation will skips refreshing the mpath status every time toggle mpath . This happens because enabling or disabling mpath occurs in maintenance mode, where the result must be **disable** from `host = session.xenapi.host.get_record(hostref)` under the maintenance mode.
Customers are likely to encounter issues sooner or later, which could result in an XSI ticket soon..
A better solution would be to check the actual XAPI status rather than relying on whether XAPI is in a "disabled" state by invoking `host = session.xenapi.host.get_record(hostref)`. This is because a "disabled" status for XAPI does not necessarily mean it cannot respond to requests.
storage bvt: 211238
storage bst - mpath : 211239

CA-405381 Mpath Info Does Not Automatically Refresh in XC After Disabling and Enabling Multipath

---

drivers/scsiutil.py

When reading information using sg_readcap, it would be useful in the event of failure to log what the return code was so that we know what failure we're dealing with.
Also, per the manual pages for these commands, there are quite a few more return codes which should be considered retryable, plus a non-zero success return code which is theoretically possible.
Add a function to gather up the checks and logs for these things and then wrap a call to that function in a short retry loop.

CA-395560 Improve logging and error checking on sg_readcap

---

systemd/sm-mpath-root.service

The previous set of dependencies actually result in an ordering loop and aren't actually required.

CA-407566: adjust systemd dependencies

---

drivers/mpath_dmp.py
drivers/util.py

Some orders of doing things do not trigger udev events with the right timing to get the multipath config records updated when multipath is shut down entirely.
Deliberately kick the mpathcount pipe after multipath is deactivated, which will ensure that the mpathcount service runs shortly after. If it had already been kicked and had not yet run, this extra kick will have no effect.

CP-50026 Ensure mpathcount runs after multipath deactivate

---

Makefile
mk/sm.spec.in
udev/99-purestorage.rules

This commit integrates PureStorage-recommended udev rules to optimize queue settings for Citrix XenServer. These changes follow the guidelines outlined in the PureStorage Knowledge Base article [#kbid](https://support.purestorage.com/bundle/m_citrix/page/Solutions/Citrix/Citrix_XenServer/topics/task/t_applying_queue_settings_with_udev.html).
Key changes:
- Implemented udev rules to adjust IO scheduler and queue depth for PureStorage volumes.
- Ensured compliance with existing XenServer storage management (SM) conventions.
- Verified functionality through test scenarios to avoid regression with non-PureStorage configurations.
Motivation:
These changes aim to improve performance and reliability for deployments using PureStorage arrays, adhering to vendor-recommended best practices while …

Add udev rules for PureStorage - best practices

---

drivers/lvutil.py
tests/test_lvutil.py

In the previous commit eb292457c5fd5f00f6fc82454a915068ab15aa6f, we fixed an issue where the pvremove removed a device that didn't represent the PV because of multipath.
We fixed that issue by finding the real PV before removing the VG and PVs.
Now another issue occured for a similar reason: after removing the VG, LVM cache reassign the underlying device represents the PV, then we failed `pvremove dev` using the original device node.
The issue can be reproduced repeatly on XenServer 9. It might be caused by the update of lvm or multipath logic.
The solution is:
Before vgremove, save the uuid of the PVs attached to the VG. After vgremove, use the uuid to get the underlying device that represents the PV, then pvremove it.
For PV on multipathed devices, please refer to: …

CA-407507: Fix pvremove issue for multipathed devices

---

udev/99-purestorage.rules

Restore udev configuration line deleted by error in PR [#729](https://github.com/xapi-project/sm/pull/729)
Related discussion: [https://github.com/xapi-project/sm/pull/729#discussion_r1982945403](https://github.com/xapi-project/sm/pull/729#discussion_r1982945403)

iSCSI udev rules for PureStorage - Correction of an old PR (#729)

---

drivers/SR.py

Kickpipe as subprocess to run mpathcount script in the background to avoid the synchronously calling block the SR attach process.
The original implementation will pass a `SCSIid` to the mpathcount script, however I think this script will not handler a extra parameter at the moment. so it is an unnecessary parameter.
BST - 214740 
Limit configure test -  21474

CP-53692 SR attach calls mpathcount async

---

misc/fairlock/fairlock@.service

When shutting down or rebooting, Xapi will call things in SM which want to use the fairlock service, but newer systemd will refuse to start it because it already has it stopping as part of the current transaction.
Ensure systemd does not stop fairlock until after Xapi, to prevent this from being a problem.

Prevent fairlock from being stopped before xapi

---

drivers/lcache.py
tests/test_lcache.py

The connection from the leaf (per-vm) tapdisk to the shared parent tapdisk when using IntelliCache now uses NBD rather than the kernel blktap device. This causes the tapdisk-cache-stats script to fail and exit with error 1. As a result no IntelliCache stats are produced, fix this by adding support for the remote to be nbd to a defined path.

CA-409231: report intellicache stats with nbd

---

Makefile
compat-libs/resetvdis.py
libs/sm/resetvdis.py
utils/resetvdis

The resetvdis compatibility library is no longer required. Instead, the executable part of resetvdis.py needs to move under /usr/libexec with a symlink from the old name for compatiblility

CP-308219 Separate resetvdis script

---

libs/sm/cleanup.py
systemd/SMGC@.service
tests/test_cleanup.py

The xapi enabled state does not reflect whether the local xapi process is able to respond to requests and only whether the host is enabled to run new VMs. It is therefore not a useful check to ensure the GC will be able to make requests of xapi. Switch instead to making the service require the xapi-init-complete.target which will at least ensure the local xapi has completed its initialisation which was the original intent of this check.

CA-395221: use systemd target for gc enable

---

utils/mpathcount

This also addresses a logging issue in the error path which has been present since 2018 or so.

Modernise log formatting in mpathcount

---

Makefile

The tapdisk-cache-stats script imports sm.lcache but the module wasn't being installed due to missing entry in Makefile's SM_LIBS list.
(rerun 4352152 passed)

CA-412080 Add lcache to SM_LIBS to resolve tapdisk-cache-stats import error

---

scripts/stop_all_gc

systemd has changed its output for command as folllows /usr/bin/systemctl list-units SMGC@*
============>
SMGC@1.service
SMGC@2.service
============
SMGC@1.service
SMGC@2.service
<============
Note: the extra space before the valid service name This means `cut -d' ' -f1` can no longer parse the service name. `awk` is used rather that `cut` to fix the issue

CA-405851: stop_all_gc failed to stop SMGC services
